server:
  port: 8080

spring:
  application:
    name: mravel-gateway

  cloud:
    gateway:
      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        # USER SERVICE
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        # CATALOG SERVICE
        - id: catalog-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/catalog/**

        # BOOKING SERVICE (port 8084)
        - id: booking-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/bookings/**

        # PLAN SERVICE
        - id: plan-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/plans/**
          filters:
            - RewritePath=/api/plans/(?<segment>.*), /api/plans/${segment}

      # CORS setup
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

logging:
  level:
    org.springframework.cloud.gateway: DEBUG